addons:
    homebrew:
        packages:
        - python3
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

matrix:
    include:
    - os: linux
      sudo: required
      python: "3.6"
      language: python
      env:
      - PLUGIN_EXT=so
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      language: cpp
      env:
      - PLUGIN_EXT=scx
      - MATRIX_EVAL=":"

before_install:
- eval "${MATRIX_EVAL}"
- pip3 install cookiecutter
- git clone --depth 1 https://github.com/supercollider/supercollider.git ../supercollider

before_script:
- cd ..

- echo $PWD/supercollider >>cmds # sc path
- echo TEST_PROJECT_NAME >>cmds
- echo TEST_NAMESPACE >>cmds
- echo TEST_REPO_NAME >>cmds
- echo TEST_PLUGIN_NAME >> cmds
- echo "Test plugin description" >>cmds
- echo "Test full name" >> cmds
- echo TestGithubUsername >>cmds
- echo 'test@username.com' >>cmds
- cookiecutter cookiecutter-supercollider-plugin <cmds

- cd TEST_REPO_NAME
- echo "CMake file contents:"
- cat CMakeLists.txt

- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=_install -DSTRICT=ON ..

script:
- cmake --build . --target install

after_script:
- echo "sc file contents:"
- cat _install/TEST_PROJECT_NAME/TEST_PLUGIN_NAME/Classes/TEST_PLUGIN_NAME.sc

- echo "schelp file contents:"
- cat _install/TEST_PROJECT_NAME/TEST_PLUGIN_NAME/HelpSource/Classes/TEST_PLUGIN_NAME.schelp

- echo "testing existence of plugin files:"
- 'if [[ ! -f _install/TEST_PROJECT_NAME/TEST_PLUGIN_NAME/TEST_PLUGIN_NAME_scsynth.$PLUGIN_EXT ]]; then exit 1; fi;'
- 'if [[ ! -f _install/TEST_PROJECT_NAME/TEST_PLUGIN_NAME/TEST_PLUGIN_NAME_supernova.$PLUGIN_EXT ]]; then exit 1; fi;'
